controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}/api
    requirements:
        _locale: '%app_locales%'
    defaults:
        _locale: '%locale%'
kernel:
    resource: ../../src/Kernel.php
    type: annotation
